// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGiD-0cpUFavDwq8wKIle1qzeiz1x7cU',
    appId: '1:83334746033:web:1155829d2b19c070f53790',
    messagingSenderId: '83334746033',
    projectId: 'good-monning',
    authDomain: 'good-monning.firebaseapp.com',
    storageBucket: 'good-monning.appspot.com',
    measurementId: 'G-PZDTLKVNG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_UBrjNO62eoFoAS_ZX_8HSExMSO63mU',
    appId: '1:83334746033:android:66de75229ecef7b2f53790',
    messagingSenderId: '83334746033',
    projectId: 'good-monning',
    storageBucket: 'good-monning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVjla3btD9oRt-pOoPdfaurksaSg4NdPk',
    appId: '1:83334746033:ios:29674d16e1df1f9af53790',
    messagingSenderId: '83334746033',
    projectId: 'good-monning',
    storageBucket: 'good-monning.appspot.com',
    iosClientId: '83334746033-04oepsetf5qdsll9b8q3vlup0qo7tuv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodMonning',
  );
}
